language: java
dist: xenial

services:
  - docker

jdk:
  - openjdk8

node_js:
  - 10

cache:
  npm: true
  directories:
    - $HOME/.m2
    - node_modules

branches:
  only:
    - develop
    - master

script:
  - cd frontend
  - npm ci --quiet
  - npm run build:prod
  - cd ..
  - cd backend
  - ./mvnw clean package -DskipTests=true -q
  - cd ..
  - docker build . -t kafka-viewer

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master