version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - java -version
      - mvn --version
      - node --version
      - npm --version
      - docker --version
  build:
    commands:
      - cd frontend
      - npm ci --quiet
      - npm run build:prod
      - cd ..
      - cd backend
      - mvn clean package -DskipTests=true -q
      - cd ..
      - docker build . -t kafka-viewer