version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/dockerhub/username"
    DOCKER_PASSWORD: "/dockerhub/password"
    DOCKER_REGISTRY: "/dockerhub/registry"
    DOCKER_IMAGE: "/dockerhub/image"

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
      java: openjdk11
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  build:
    commands:
      - cd backend
      - mvn clean package -DskipTests=true -q
      - cd ..
      - cd frontend
      - npm ci --quiet
      - npm run build:prod
      - cd ..
      - docker build . -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
