version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/dockerhub/username"
    DOCKER_PASSWORD: "/dockerhub/password"
    DOCKER_REGISTRY: "/dockerhub/registry"
    DOCKER_IMAGE: "/dockerhub/image"

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
      java: openjdk11
    commands:
      - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
  pre_build:
    commands:
      - cd backend/kafka-producer
      - mvn test
      - cd ../..
  build:
    commands:
      - cd backend
      - mvn clean package -DskipTests=true -q
      - cd ..
      - cd frontend
      - npm ci --quiet
      - npm run build:prod
      - cd ..
      - docker build . -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}
      - docker push ${DOCKER_REGISTRY}/${DOCKER_IMAGE}

reports:
  producer_tests:
    files:
      - "**/*"
    base-directory: backend/kafka-producer/target/surefire-reports
    file-format: JunitXml